import type { InstitutionalDate, InstitutionalPeriod } from './institutionalCalendar';

const sourceUrl = 'https://www.intec.edu.do/estudiantes/calendarios/calendario-anual';
const updatedAt = '2026-10-01T00:00:00-04:00';

export const annualInstitutionalPeriods = [
  {
    id: '2026-T3', title: 'Trimestre agosto–octubre 2026', startsOn: '2026-08-03', endsOn: '2026-10-17', timezone: 'America/Santo_Domingo', sourceUrl, updatedAt,
    dates: [
      { date: '2026-08-03', kind: 'milestone', title: 'Inicio de docencia', detail: 'Inicio oficial del trimestre agosto–octubre 2026.' },
      { date: '2026-08-06', kind: 'milestone', title: 'Selección tardía y modificación', detail: 'Disponible en línea y en las áreas académicas hasta el 7 de agosto.' },
      { date: '2026-08-07', kind: 'milestone', title: 'Fecha límite para solicitar tutorías', detail: 'Último día para que las áreas remitan las solicitudes a Registro.' },
      { date: '2026-08-10', kind: 'milestone', title: 'Inicia el retiro de asignaturas', detail: 'El retiro está disponible únicamente en línea hasta el 3 de octubre.' },
      { date: '2026-08-16', kind: 'no_class', title: 'Día de la Restauración', detail: 'No hay actividades académicas por el feriado nacional.' },
      { date: '2026-08-31', kind: 'milestone', title: 'Evaluaciones de medio término', detail: 'El período de evaluaciones finaliza el 5 de septiembre.' },
      { date: '2026-09-11', kind: 'milestone', title: 'Fecha límite para cambio de carrera', detail: 'Finaliza el período iniciado el 10 de agosto.' },
      { date: '2026-09-24', kind: 'no_class', title: 'Nuestra Señora de las Mercedes', detail: 'No hay actividades académicas por el feriado nacional.' },
      { date: '2026-09-26', kind: 'milestone', title: 'Calificaciones de medio término', detail: 'Fecha límite para reportar las calificaciones de medio término.' },
      { date: '2026-10-02', kind: 'milestone', title: 'Fecha límite para solicitar grado', detail: 'Aplica a la graduación de abril de 2027.' },
      { date: '2026-10-03', kind: 'milestone', title: 'Último día para retirar asignaturas', detail: 'El retiro está disponible únicamente en línea.' },
      { date: '2026-10-10', kind: 'milestone', title: 'Ceremonia de graduación', detail: 'Actividad institucional sujeta a cambio.' },
      { date: '2026-10-12', kind: 'milestone', title: 'Última semana de docencia', detail: 'Docencia y evaluaciones finales hasta el 17 de octubre.' },
      { date: '2026-10-17', kind: 'milestone', title: 'Finaliza la docencia', detail: 'Último día del trimestre agosto–octubre 2026.' },
      { date: '2026-10-20', kind: 'milestone', title: 'Calificaciones finales', detail: 'Fecha límite de entrega para el trimestre.' },
      { date: '2026-10-30', kind: 'milestone', title: 'Calificaciones de incompletos', detail: 'Fecha límite de entrega para el trimestre.' },
    ] satisfies InstitutionalDate[],
  },
  {
    id: '2026-T4', title: 'Trimestre noviembre 2026–enero 2027', startsOn: '2026-11-02', endsOn: '2027-01-23', timezone: 'America/Santo_Domingo', sourceUrl, updatedAt,
    dates: [
      { date: '2026-10-06', kind: 'milestone', title: 'Preselección de asignaturas', detail: 'Disponible en línea hasta el 12 de octubre.' },
      { date: '2026-10-09', kind: 'milestone', title: 'Fecha límite para solicitar reingreso', detail: 'Aplica al trimestre noviembre 2026–enero 2027.' },
      { date: '2026-10-20', kind: 'milestone', title: 'Selección de nuevo ingreso', detail: 'Selección de asignaturas para estudiantes de grado.' },
      { date: '2026-10-22', kind: 'milestone', title: 'Selección de posgrado', detail: 'Selección de asignaturas para estudiantes de posgrado.' },
      { date: '2026-10-27', kind: 'milestone', title: 'Selección de estudiantes activos', detail: 'Disponible en línea hasta el 29 de octubre.' },
      { date: '2026-11-02', kind: 'milestone', title: 'Inicio de docencia', detail: 'Inicio oficial del trimestre noviembre 2026–enero 2027.' },
      { date: '2026-11-05', kind: 'milestone', title: 'Selección tardía y modificación', detail: 'Disponible hasta el 6 de noviembre.' },
      { date: '2026-11-09', kind: 'no_class', title: 'Día de la Constitución', detail: 'No hay actividades académicas por el feriado trasladado.' },
      { date: '2026-11-30', kind: 'milestone', title: 'Evaluaciones de medio término', detail: 'El período de evaluaciones finaliza el 5 de diciembre.' },
      { date: '2026-12-11', kind: 'milestone', title: 'Fecha límite para cambio de carrera', detail: 'Finaliza el período iniciado el 10 de noviembre.' },
      { date: '2026-12-24', endsOn: '2027-01-03', kind: 'no_class', title: 'Asueto de Navidad', detail: 'No hay actividades académicas del 24 de diciembre al 3 de enero.' },
      { date: '2027-01-01', kind: 'no_class', title: 'Año Nuevo', detail: 'No hay actividades académicas por el feriado nacional.' },
      { date: '2027-01-04', kind: 'no_class', title: 'Día de los Santos Reyes', detail: 'No hay actividades académicas por el feriado trasladado.' },
      { date: '2027-01-08', kind: 'milestone', title: 'Fecha límite para solicitar grado', detail: 'Aplica a la graduación de abril de 2027.' },
      { date: '2027-01-09', kind: 'milestone', title: 'Último día para retirar asignaturas', detail: 'El retiro está disponible únicamente en línea.' },
      { date: '2027-01-18', kind: 'milestone', title: 'Última semana de docencia', detail: 'Docencia y evaluaciones finales hasta el 23 de enero.' },
      { date: '2027-01-21', kind: 'no_class', title: 'Nuestra Señora de la Altagracia', detail: 'No hay actividades académicas por el feriado nacional.' },
      { date: '2027-01-23', kind: 'milestone', title: 'Finaliza la docencia', detail: 'Último día del trimestre noviembre 2026–enero 2027.' },
      { date: '2027-01-25', kind: 'no_class', title: 'Natalicio de Juan Pablo Duarte', detail: 'No hay actividades académicas por el feriado trasladado.' },
      { date: '2027-01-26', kind: 'milestone', title: 'Calificaciones finales', detail: 'Fecha límite de entrega para el trimestre.' },
      { date: '2027-01-29', kind: 'milestone', title: 'Calificaciones de incompletos', detail: 'Fecha límite de entrega para el trimestre.' },
    ] satisfies InstitutionalDate[],
  },
  {
    id: '2027-T1', title: 'Trimestre febrero–abril 2027', startsOn: '2027-02-01', endsOn: '2027-04-24', timezone: 'America/Santo_Domingo', sourceUrl, updatedAt,
    dates: [
      { date: '2027-01-12', kind: 'milestone', title: 'Preselección de asignaturas', detail: 'Disponible en línea hasta el 18 de enero.' },
      { date: '2027-01-15', kind: 'milestone', title: 'Fecha límite para solicitar reingreso', detail: 'Aplica al trimestre febrero–abril 2027.' },
      { date: '2027-01-19', kind: 'milestone', title: 'Selección de nuevo ingreso', detail: 'Selección de asignaturas para estudiantes de grado.' },
      { date: '2027-01-22', kind: 'milestone', title: 'Selección de posgrado', detail: 'Selección de asignaturas para estudiantes de posgrado.' },
      { date: '2027-01-26', kind: 'milestone', title: 'Selección de estudiantes activos', detail: 'Disponible en línea hasta el 28 de enero.' },
      { date: '2027-02-01', kind: 'milestone', title: 'Inicio de docencia', detail: 'Inicio oficial del trimestre febrero–abril 2027.' },
      { date: '2027-02-04', kind: 'milestone', title: 'Selección tardía y modificación', detail: 'Disponible hasta el 5 de febrero.' },
      { date: '2027-02-27', kind: 'no_class', title: 'Día de la Independencia Nacional', detail: 'No hay actividades académicas por el feriado nacional.' },
      { date: '2027-03-01', kind: 'milestone', title: 'Evaluaciones de medio término', detail: 'Período institucional de evaluaciones según el calendario anual.' },
      { date: '2027-03-12', kind: 'milestone', title: 'Fecha límite para cambio de carrera', detail: 'Finaliza el período iniciado el 8 de febrero.' },
      { date: '2027-03-21', endsOn: '2027-03-28', kind: 'no_class', title: 'Asueto de Semana Santa', detail: 'No hay actividades académicas del 21 al 28 de marzo.' },
      { date: '2027-04-09', kind: 'milestone', title: 'Fecha límite para solicitar grado', detail: 'Aplica a la graduación de octubre de 2027.' },
      { date: '2027-04-10', kind: 'milestone', title: 'Último día para retirar asignaturas', detail: 'El retiro está disponible únicamente en línea.' },
      { date: '2027-04-17', kind: 'milestone', title: 'Ceremonia de graduación', detail: 'Actividad institucional sujeta a cambio.' },
      { date: '2027-04-19', kind: 'milestone', title: 'Última semana de docencia', detail: 'Docencia y evaluaciones finales hasta el 24 de abril.' },
      { date: '2027-04-24', kind: 'milestone', title: 'Finaliza la docencia', detail: 'Último día del trimestre febrero–abril 2027.' },
      { date: '2027-04-27', kind: 'milestone', title: 'Calificaciones finales', detail: 'Fecha límite de entrega para el trimestre.' },
      { date: '2027-04-30', kind: 'milestone', title: 'Calificaciones de incompletos', detail: 'Fecha límite de entrega para el trimestre.' },
    ] satisfies InstitutionalDate[],
  },
  {
    id: '2027-T2', title: 'Trimestre mayo–julio 2027', startsOn: '2027-05-03', endsOn: '2027-07-17', timezone: 'America/Santo_Domingo', sourceUrl, updatedAt,
    dates: [
      { date: '2027-04-13', kind: 'milestone', title: 'Preselección de asignaturas', detail: 'Disponible en línea hasta el 19 de abril.' },
      { date: '2027-04-16', kind: 'milestone', title: 'Fecha límite para solicitar reingreso', detail: 'Aplica al trimestre mayo–julio 2027.' },
      { date: '2027-04-20', kind: 'milestone', title: 'Selección de nuevo ingreso', detail: 'Selección de asignaturas para estudiantes de grado.' },
      { date: '2027-04-22', kind: 'milestone', title: 'Selección de posgrado', detail: 'Selección de asignaturas para estudiantes de posgrado.' },
      { date: '2027-04-27', kind: 'milestone', title: 'Selección de estudiantes activos', detail: 'Disponible en línea hasta el 29 de abril.' },
      { date: '2027-04-30', kind: 'no_class', title: 'Día del Trabajo', detail: 'No hay actividades académicas por el feriado trasladado.' },
      { date: '2027-05-03', kind: 'milestone', title: 'Inicio de docencia', detail: 'Inicio oficial del trimestre mayo–julio 2027.' },
      { date: '2027-05-06', kind: 'milestone', title: 'Selección tardía y modificación', detail: 'Disponible hasta el 7 de mayo.' },
      { date: '2027-05-27', kind: 'no_class', title: 'Corpus Christi', detail: 'No hay actividades académicas por el feriado nacional.' },
      { date: '2027-05-31', kind: 'milestone', title: 'Evaluaciones de medio término', detail: 'El período de evaluaciones finaliza el 5 de junio.' },
      { date: '2027-06-11', kind: 'milestone', title: 'Fecha límite para cambio de carrera', detail: 'Finaliza el período iniciado el 10 de mayo.' },
      { date: '2027-07-02', kind: 'milestone', title: 'Fecha límite para solicitar grado', detail: 'Aplica a la graduación de octubre de 2027.' },
      { date: '2027-07-03', kind: 'milestone', title: 'Último día para retirar asignaturas', detail: 'El retiro está disponible únicamente en línea.' },
      { date: '2027-07-12', kind: 'milestone', title: 'Última semana de docencia', detail: 'Docencia y evaluaciones finales hasta el 17 de julio.' },
      { date: '2027-07-17', kind: 'milestone', title: 'Finaliza la docencia', detail: 'Último día del trimestre mayo–julio 2027.' },
      { date: '2027-07-20', kind: 'milestone', title: 'Calificaciones finales', detail: 'Fecha límite de entrega para el trimestre.' },
      { date: '2027-07-30', kind: 'milestone', title: 'Calificaciones de incompletos', detail: 'Fecha límite de entrega para el trimestre.' },
    ] satisfies InstitutionalDate[],
  },
] satisfies InstitutionalPeriod[];
