openapi: 3.0.1
info:
  title: bnbdo API
  description: 'Tenant and rental management module'
  version: 1.0.0

x-amazon-api-gateway-request-validators:
  Validate body, query string parameters, and headers:
    validateRequestBody: true
    validateRequestParameters: true
  Validate body:
    validateRequestBody: true
    validateRequestParameters: false
  Validate query string parameters and headers:
    validateRequestBody: false
    validateRequestParameters: true

paths:
  /health:
    $ref: './services/user.yaml#/search-users'

components:
  securitySchemes:
    ApiKey:
      $ref: './components/security.yaml#/ApiKey'